
nginx_conf_dir: /etc/nginx
nginx_sites_dir: "{{ nginx_conf_dir }}/sites-enabled"

rstudio_version: 1.1.383
rstudio_package_url: "http://download2.rstudio.org/rstudio-server-{{ rstudio_version }}-amd64.deb"
rstudio_local_tmp_package: /tmp/rstudio-server.deb

modules_home: /usr/share/modules/modulefiles

jupyterhub_location: /jupyter/
jupyterhub_port: 9510
# jupyter dependent versions
jupyterhub_version: 1.0.0
configurable_http_proxy_version: 3.1.1
ipython_notebook_version: 7.5.0
matplotlib_version: 3.0.3
scipy_version: 1.3.0
pandas_version: 0.24.2

new_user: researcher
use_ubuntu_password: "yes"
homedir_path: /mnt/galaxy/home
user_shell: /bin/bash

cloudman_config_file: /opt/cloudman/boot/userData.yaml

gvl_cmdlineutils_version: "4.3.0"
gvl_cmdlineutils_build_date: "{{ ansible_date_time.iso8601 }}"
gvl_install_path: /opt/gvl

